package yourfrog.jump;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import jsyntaxpane.DefaultSyntaxKit;
import yourfrog.jump.operationTree.OperationJTree;
import yourfrog.jump.operationTree.listener.SelectedItem;
import yourfrog.jump.resultTabbedPane.ResultTabbedPane;
import yourfrog.jump.resultTabbedPane.listener.SelectedTab;

/**
 *
 * @author YourFrog
 */
public class MainFrame extends JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super("Jumper !");
        
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        ResultTabbedPane tabPane = new ResultTabbedPane();
        
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.setTabPlacement(JTabbedPane.BOTTOM);
        
        OperationJTree tree = new OperationJTree(tabPane);
        tree.addMouseListener(new SelectedItem(tree, tabbedPane));
        tree.setSize(350, 400);
        tree.setFont(tree.getFont().deriveFont(10.0f));

        JScrollPane treeScroll = new JScrollPane(tree);
        
        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, treeScroll, tabbedPane);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(350);
        
        tabPane.addMouseListener(new SelectedTab(tabPane, tabbedPane));
        JScrollPane treeScroll3 = new JScrollPane(tabPane);
        tree.setMinimumSize(new Dimension(500, 400));
        
        JSplitPane verticalPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, splitPane, treeScroll3);
        verticalPane.setSize(getWidth(), getContentPane().getHeight());
        verticalPane.setDividerLocation(550);
        
        this.getContentPane().add(verticalPane);
        
        setLayout(new GridLayout(0, 1));
        
        DefaultSyntaxKit.initKit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
